meta_product_name: "TJP Wattignies"
meta_title: "TJP Wattignies"
meta_description: "Le TJP de Wattignies c'est un tournoi réunissant 60 équipes de jeunes de France et d'Europe pour partager les valeurs du hockey sur gazon dans la convivialité et l'amusement !"
meta_image: "cover_tjp.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account" # required for Twitter Cards
